// export const API_URL = PROCESS_ENV_API_URL
// ..AUTH
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

// UNAUTH
export const SIGNOUT = 'SIGNOUT'

// ..SIGNUP
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

// ...CODE
export const RESENDCODE_SUCCESS = 'RESENDCODE_SUCCESS'
export const RESENDCODE_FAIL = 'RESENDCODE_FAIL'
// ...
export const VERIFYCODE_SUCCESS = 'VERIFYCODE_SUCCESS'
export const VERIFYCODE_FAIL = 'VERIFYCODE_FAIL'

// ...ERRORS
export const CLEAR_SERVER_ERRORS = 'CLEAR_SERVER_ERRORS'